name: TrindadeWare Debug

on:
  push:
    branches:
      - main
      - dev
      
  workflow_dispatch:
jobs:
  build:
    name: Building app by trindadeDev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: set up JDK 17
        uses: actions/setup-java@v3.3.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build with gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug

      - name: Upload debug apk minApi26
        uses: actions/upload-artifact@v3
        with:
          name: trindade-ware-debug
          path: app/build/outputs/apk/trindade-ware-debug
